<?php if (!count($requests)) { ?>
<h4 class="text-center text-muted">
    <?=H(T('暂无数据'))?>
</h4>
<?php } else { ?>
    <ul class="list-unstyled">
    <?php foreach ($requests as $vRequest) { ?>
        <li>
            <?=$vRequest->cas_no ? H(T(':ctime :owner 申请了 :cas 上限到 :volume', [
                ':ctime'=> $vRequest->ctime,
                ':owner'=> $vRequest->owner->name,
                ':cas'=> $vRequest->name ?: $vRequest->cas_no,
                ':volume'=> $vRequest->volume,
            ])) : H(T(':ctime :owner 申请了 :type 上限到 :volume', [
                ':ctime'=> $vRequest->ctime,
                ':owner'=> $vRequest->owner->name,
                ':type'=> $vRequest->type,
                ':volume'=> $vRequest->volume,
            ]))?>
        <li>
    <?php }?>
    </ul>
	<ul class="list-unstyled text-center">
	<?php
		$vPFrom = (ceil($page/10) - 1) * 10 + 1;
		$vPTo = min(ceil($page/10) * 10 +1, $total);
		if ($vPT - $vPFrom < 11) {
		$vPFrom = max(1, $vPTo - 11);
		}
	?>
	<?php if ($vPFrom!=1) {?>
        <li class="<?=($page==1) ? 'app-pager-li-active' : ''?>"><a href="inventory/requests/1"><?=H(T('首页'))?></a></li>
	<?php }?>
	<?php for ($i=$vPFrom; $i<=$vPTo; $i++) {?>
        <li class="<?=($page==$i) ? 'app-pager-li-active' : ''?>"><a href="inventory/requests/<?=H($i)?>"><?=H($i)?></a></li>
	<?php }?>
	<?php if ($vPTo!=$total) {?>
		<li class="<?=($page==$total) ? 'app-pager-li-active' : ''?>"><a href="inventory/requests/<?=H($total)?>"><?=H(T('尾页'))?></a></li>
	<?php }?>
	</ul>
<?php } ?>


