<?php if (!count($requests)) { ?>
<h4 class="text-center text-muted">
    <?=H(T('暂无数据'))?>
</h4>
<?php } else { ?>
    <?php foreach ($requests as $vRequest) { ?>
        <div class="board-content-request-li"><div class="clearfix row">
            <div class="pull-right app-handler-container" data-id="<?=H($vRequest->id)?>">
                <?php if ($vRequest->status==\Gini\ORM\Inventory\Request::STATUS_PENDING) {?>
                    <span class="btn btn-primary btn-sm app-handler-approve-request"><?=H(T('通过'))?></span>
                    <span class="btn btn-default btn-sm app-handler-reject-request"><?=H(T('拒绝'))?></span>
                <?php } else { ?>
                    <?=H(\Gini\ORM\Inventory\Request::getStatusTitle($vRequest->status))?>
                <?php } ?>
            </div>
            <div>
                <div><?=$vRequest->cas_no ? T(':ctime :owner 申请了 :cas 上限到 :volume', [
                    ':ctime'=> "<span class=\"text-muted\">{$vRequest->ctime}</span>",
                    ':owner'=> "<strong>{$vRequest->owner->name}</strong>",
                    ':cas'=> "<strong>{$vRequest->name}</strong>",
                    ':volume'=> "<strong>{$vRequest->volume}</strong>",
                ]) : T(':ctime :owner 申请了 :type 上限到 :volume', [
                    ':ctime'=> "<span class=\"text-muted\">{$vRequest->ctime}</span>",
                    ':owner'=> "<strong>{$vRequest->owner->name}</strong>",
                    ':type'=> '<strong>' . \Gini\ORM\Inventory\Reagent::$default_cas_nos[$vRequest->type] . '</strong>',
                    ':volume'=> "<strong>{$vRequest->volume}</strong>",
                ])?></div>
                <?php if ($vRequest->reason) {?>
                <div class="board-content-request-li-reason"><?=H($vRequest->reason)?></div>
                <?php }?>

                <?php if ($vRequest->status == \Gini\ORM\Inventory\Request::STATUS_APPROVED) {?>
                <div class="board-content-request-li-op">
                    <?=H(T(':time 被:op 批准', [
                        ':time'=> $vRequest->approve_time,
                        ':op'=> $vRequest->approve_man->name
                    ]))?>
                </div>
                <?php } else if ($vRequest->status == \Gini\ORM\Inventory\Request::STATUS_REJECTED) { ?>
                <div class="board-content-request-li-op">
                    <?=H(T(':time 被 :op 拒绝', [
                        ':time'=> $vRequest->reject_time,
                        ':op'=> $vRequest->reject_man->name
                    ]))?>
                </div>
                <?php } ?>
            </div>
        </div></div>
    <?php }?>
	<ul class="list-unstyled text-center">
	<?php
		$vPFrom = (ceil($page/10) - 1) * 10 + 1;
		$vPTo = min(ceil($page/10) * 10 +1, $total);
		if ($vPT - $vPFrom < 11) {
		$vPFrom = max(1, $vPTo - 11);
		}
	?>
	<?php if ($vPFrom!=1) {?>
        <li class="app-pager-li-handler<?=($page==1) ? ' app-pager-li-active' : ''?>"><a href="inventory/requests/1"><?=H(T('首页'))?></a></li>
	<?php }?>
	<?php for ($i=$vPFrom; $i<=$vPTo; $i++) {?>
        <li class="app-pager-li-handler<?=($page==$i) ? ' app-pager-li-active' : ''?>"><a href="inventory/requests/<?=H($i)?>"><?=H($i)?></a></li>
	<?php }?>
	<?php if ($vPTo!=$total) {?>
		<li class="app-pager-li-handler<?=($page==$total) ? ' app-pager-li-active' : ''?>"><a href="inventory/requests/<?=H($total)?>"><?=H(T('尾页'))?></a></li>
	<?php }?>
	</ul>
<?php } ?>


