<?php if (!count($requests)) { ?>
<h4 class="text-center text-muted">
    <?=H(T('暂无数据'))?>
</h4>
<?php } else { ?>
    <?php foreach ($requests as $vRequest) { ?>
        <div class="board-content-request-li"><div class="row">
            <div class="col-md-8">
                <div><?=$vRequest->cas_no ? H(T(':ctime :owner 申请了 :cas 上限到 :volume', [
                    ':ctime'=> $vRequest->ctime,
                    ':owner'=> $vRequest->owner->name,
                    ':cas'=> $vRequest->name ?: $vRequest->cas_no,
                    ':volume'=> $vRequest->volume,
                ])) : H(T(':ctime :owner 申请了 :type 上限到 :volume', [
                    ':ctime'=> $vRequest->ctime,
                    ':owner'=> $vRequest->owner->name,
                    ':type'=> \Gini\ORM\Inventory\Reagent::$default_cas_nos[$vRequest->type],
                    ':volume'=> $vRequest->volume,
                ]))?></div>
                <div><?=H($vRequest->reason)?></div>
            </div>
            <div class="col-md-4 text-right app-handler-container" data-id="<?=H($vRequest->id)?>">
                <?php if ($vRequest->status==\Gini\ORM\Inventory\Request::STATUS_PENDING) {?>
                    <span class="btn btn-primary btn-sm app-handler-approve-request"><?=H(T('通过'))?></span>
                    <span class="btn btn-default btn-sm app-handler-reject-request"><?=H(T('拒绝'))?></span>
                <?php } else { ?>
                    <?=H(\Gini\ORM\Inventory\Request::getStatusTitle($vRequest->status))?>
                <?php } ?>
            </div>
        </div></div>
    <?php }?>
	<ul class="list-unstyled text-center">
	<?php
		$vPFrom = (ceil($page/10) - 1) * 10 + 1;
		$vPTo = min(ceil($page/10) * 10 +1, $total);
		if ($vPT - $vPFrom < 11) {
		$vPFrom = max(1, $vPTo - 11);
		}
	?>
	<?php if ($vPFrom!=1) {?>
        <li class="app-pager-li-handler<?=($page==1) ? ' app-pager-li-active' : ''?>"><a href="inventory/requests/1"><?=H(T('首页'))?></a></li>
	<?php }?>
	<?php for ($i=$vPFrom; $i<=$vPTo; $i++) {?>
        <li class="app-pager-li-handler<?=($page==$i) ? ' app-pager-li-active' : ''?>"><a href="inventory/requests/<?=H($i)?>"><?=H($i)?></a></li>
	<?php }?>
	<?php if ($vPTo!=$total) {?>
		<li class="app-pager-li-handler<?=($page==$total) ? ' app-pager-li-active' : ''?>"><a href="inventory/requests/<?=H($total)?>"><?=H(T('尾页'))?></a></li>
	<?php }?>
	</ul>
<?php } ?>


