<?=V('inventory/header', [
    'current'=> 'setting',
])?>
<div class="board-content manager-setting-page" id="manager-setting" data-require="page/manager/member">
    <div class="row">
        <div class="col-xs-9">
            <div class="permission-cards">
                <div class="permission-group">
                    <div class="row permission-group-body">
                        <?php if (count($groups)) {?>
                            <?php foreach ($groups as $vI=>$vGroup) { ?>
                                <div class="column col-xs-6">
                                    <?=V('inventory/manager/permission-card', ['group'=> $vGroup])?>
                                </div>
                            <?php } ?>
                        <?php } ?>
                        <?php if ($me->isAllowedTo('管理权限')) {?>
                            <div class="column col-xs-6">
                                <h4 class="permission-card-group-add-handler"><span class="fa fa-plus"></span></h4>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-3 access-members">
            <div class="search-form">
                <h4><?=H(T('成员列表'))?></h4>
                <div class="search-bar form-group">
                    <form method="POST" data-form="<?= J((object)$form) ?>" >
                        <div class="input-group-unity input-group-unity-right">
                            <input type="text" class="form-control" name="q" value="<?= H($form['q']) ?>">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-default btn-search-members app-add-member-refresh-handler"><i class="fa fa-fw fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="search-results">
                <div class="loading text-center">
                    <i class="fa fa-2x fa-spinner fa-spin"></i>
                </div>
                <div class="user-icon pull-left app-add-member-handler" data-require="gapper/client/add-member">
                    <div class="user-icon-image text-center">
                        <div class="user-icon-text user-icon-text-add">
                            <span class="user-icon-text-add-handler">+</span>
                        </div>
                    </div>
                    <div class="nowrap text-center"><?=H(T('添加成员'))?></div>
                </div>
            </div>
        </div>
    </div>
</div>
